/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // 1. Primary: Solar Orange (#F06926)
        primary: "#F06926",
        "primary-hover": "#D95618",
        "primary-dark": "#B8480E",
        "primary-light": "#FFF3EC",
        "brand-orange": "#F06926",
        "brand-primary": "#F06926",
        "elleyhill-orange": "#F06926",

        // 2. Secondary: Clean Energy Green (#009047)
        secondary: "#009047",
        "secondary-hover": "#007A3D",
        "secondary-dark": "#005F2E",
        "secondary-light": "#E8F7EE",
        "brand-green": "#009047",
        "brand-secondary": "#009047",
        "primary-green": "#009047",
        "brand-primary-green": "#009047",
        "elleyhill-green": "#009047",

        // 3. Accent 1: Charcoal Slate (#393939)
        charcoal: "#393939",
        "charcoal-dark": "#262626",
        "charcoal-light": "#4A4A4A",
        "brand-dark": "#393939",
        "brand-charcoal": "#393939",
        "accent-dark": "#393939",
        "accent-charcoal": "#393939",
        "text-charcoal": "#393939",

        // 4. Accent 2: Solar Lime / Chartreuse (#B9D432)
        accent: "#B9D432",
        "accent-lime": "#B9D432",
        "accent-yellow": "#B9D432",
        "brand-lime": "#B9D432",
        "brand-accent": "#B9D432",
        "brand-yellow": "#B9D432",
        "elleyhill-yellow": "#B9D432",
        "elleyhill-lime": "#B9D432",

        // Surfaces and Containers
        "surface-container-lowest": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#f0f2f4",
        "surface-container-low": "#f8f9fa",
        "secondary-container": "#e6f5ed",
        "tertiary-fixed": "#f2f7d2",
        background: "#ffffff",
        "on-background": "#393939",
        "on-tertiary-fixed-variant": "#4a5710",
        "border-light": "rgba(0,0,0,0.08)",
        "on-tertiary-container": "#4a5710",
        "outline-variant": "#e1e3e4",
        "surface-bright": "#ffffff",
        "status-success": "#009047",
        "on-primary-fixed": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container": "#f1f3f5",
        outline: "#7e7576",
        "on-surface": "#393939",
        "surface-container-high": "#e8ebed",
        "on-secondary-container": "#004d26",
        "on-error": "#ffffff",
        "secondary-fixed": "#c4ecd4",
        "border-medium": "rgba(0,0,0,0.12)",
        "on-secondary-fixed-variant": "#004d26",
        "on-surface-variant": "#595959",
        "inverse-on-surface": "#ffffff",
        "inverse-surface": "#393939",
        error: "#ba1a1a",
        "inverse-primary": "#ffb68f",
        "on-tertiary-fixed": "#393939",
        "on-secondary-fixed": "#004d26",
        "tertiary-fixed-dim": "#dce990",
        "primary-container": "#fff1ea",
        "primary-fixed": "#ffdbc9",
        "on-tertiary": "#393939",
        "on-primary-container": "#6d2200",
        "surface-tint": "#F06926",
        "surface-container-highest": "#dfe3e6",
        "text-secondary": "#595959",
        "surface-dim": "#e2e6e9",
        "primary-fixed-dim": "#ffb68f",
        "on-primary-fixed-variant": "#852b00",
        "tertiary-container": "#edf5bc",
        "secondary-fixed-dim": "#a3dfb9",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        tertiary: "#393939",
        surface: "#ffffff",
        "brand-status-green": "#009047",
        "brand-light-tint": "#f3faf5",
        "light-tint-grey": "#f8f9fa",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
        card: "12px",
        bento: "16px",
        button: "8px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-lg": "32px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "container-max": "1440px",
        gutter: "24px",
        "header-height-mobile": "60px",
        "stack-md": "16px",
        "header-height-desktop": "72px",
      },
      fontFamily: {
        "display-hero-mobile": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "display-hero": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "label-cta": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "technical-data": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-md": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "headline-lg": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        inter: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "display-hero-mobile": ["32px", { lineHeight: "1.1", fontWeight: "700" }],
        "display-hero": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "1.5", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.2", fontWeight: "700" }],
        "label-cta": ["16px", { lineHeight: "1", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "1.5", fontWeight: "400" }],
        "technical-data": ["14px", { lineHeight: "1.4", letterSpacing: "0.02em", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
        "headline-lg": ["40px", { lineHeight: "1.2", fontWeight: "700" }],
      },
      boxShadow: {
        "hover-card": "0 12px 24px rgba(0,0,0,0.06)",
        interactive: "0 12px 24px rgba(0,0,0,0.06)",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
};
